### ISSUE TITLE
ppfshapematchinghalcon question

### ISSUE THREAD

**Issue by YyYyYong0331** [ilics/homebrewdb#1]
Hi ilics,

Thank you very much for this project.

But I have some problems in using it.

I'll try to use the Validation images (Primesense) you provided to see if I can generate labels.

But in ppfshapematchinghalcon step, Generated file(object_poses) is error. And then I can not refine step.
![image](https://user-images.githubusercontent.com/75367423/115043974-a1055200-9f07-11eb-817b-9ee283306a4d.png)
All frames will be skipped.

This is the dependency package I use.
![image](https://user-images.githubusercontent.com/75367423/115044026-aebad780-9f07-11eb-9e8e-025336bc7873.png)
I use the Halcon 18.11.

Can you help me?

**Comment by Matthew-CQ** [comment]
Hi Yong, 

Have you reconstructed the scene successfully in sdf_fusion? I failed on this part. 
Operation: Ubuntu18.04
